import path from "node:path";
import { ASSETS } from "./paths.js";

function s(file: string): string {
  return path.join(ASSETS.symbolsDir, file);
}

export const symbols: Record<string, string> = {
  "0": s("0.svg"),
  "1": s("1.svg"),
  "2": s("2.svg"),
  "3": s("3.svg"),
  "4": s("4.svg"),
  "5": s("5.svg"),
  "6": s("6.svg"),
  "7": s("7.svg"),
  "8": s("8.svg"),
  "9": s("9.svg"),
  "10": s("10.svg"),
  "11": s("11.svg"),
  "12": s("12.svg"),
  "13": s("13.svg"),
  "14": s("14.svg"),
  "15": s("15.svg"),
  "16": s("16.svg"),
  "17": s("17.svg"),
  "18": s("18.svg"),
  "19": s("19.svg"),
  "20": s("20.svg"),
  "100": s("100.svg"),
  "1000000": s("1000000.svg"),
  A: s("A.svg"),
  Action: s("Action.svg"),
  B: s("B.svg"),
  BG: s("BG.svg"),
  BonusAction: s("BonusAction.svg"),
  BP: s("BP.svg"),
  BR: s("BR.svg"),
  C: s("C.svg"),
  CHAOS: s("CHAOS.svg"),
  E: s("E.svg"),
  G: s("G.svg"),
  GP: s("GP.svg"),
  GU: s("GU.svg"),
  GW: s("GW.svg"),
  HALF: s("HALF.svg"),
  HR: s("HR.svg"),
  HW: s("HW.svg"),
  INFINITY: s("INFINITY.svg"),
  L: s("L.svg"),
  P: s("P.svg"),
  PB: s("PB.svg"),
  PW: s("PW.svg"),
  Q: s("Q.svg"),
  R: s("R.svg"),
  Reaction: s("Reaction.svg"),
  RG: s("RG.svg"),
  RP: s("RP.svg"),
  RW: s("RW.svg"),
  S: s("S.svg"),
  T: s("T.svg"),
  U: s("U.svg"),
  UB: s("UB.svg"),
  UP: s("UP.svg"),
  UR: s("UR.svg"),
  W: s("W.svg"),
  WB: s("WB.svg"),
  WP: s("WP.svg"),
  WU: s("WU.svg"),
  X: s("X.svg"),
  Y: s("Y.svg"),
  Z: s("Z.svg"),
  "2B": s("2B.svg"),
  "2G": s("2G.svg"),
  "2R": s("2R.svg"),
  "2U": s("2U.svg"),
  "2W": s("2W.svg"),
  D4: s("D4.png"),
  D6: s("D6.png"),
  D8: s("D8.png"),
  D10: s("D10.png"),
  D12: s("D12.png"),
  D20: s("D20.png"),
};

export type GameSymbol = keyof typeof symbols;
